-- ===============================================
-- Seed Users – Matematici Speciale
-- ===============================================

-- Creează extensia pgcrypto dacă nu există
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Inserare utilizatori
INSERT INTO users (name, email, password_hash, role, tries) VALUES
('Andrei Stefan Neacsu', 'andrei-stefan.neacsu@s.unibuc.ro', crypt('Adm1n@MS', gen_salt('bf')), 'admin', 3),
('Andrei Sebastian Nituica', 'andrei-sebastian.nituica@s.unibuc.ro', crypt('Adm1n@MS', gen_salt('bf')), 'admin', 3),
('Bălan Otniel-Andrei', 'otniel-andrei.balan@s.unibuc.ro', crypt('XzeZ2CGy5TDB89hf', gen_salt('bf')), 'student', 3),
('Chelan Maria-Estera', 'maria-estera.chelan@s.unibuc.ro', crypt('QDhV!Nu&rZMkm7?9', gen_salt('bf')), 'student', 3),
('Chelu Radu-Andrei', 'radu-andrei.chelu@s.unibuc.ro', crypt('!gfdZdPa6+%gZ6q7', gen_salt('bf')), 'student', 3),
('Ciuvică Alexandru', 'alexandru.ciuvica@s.unibuc.ro', crypt('J-6g$-86TDQD4%Dn', gen_salt('bf')), 'student', 3),
('Dragnea Edward-Dorian', 'edward-dorian.dragnea@s.unibuc.ro', crypt('V9cpngS5%?jbwqx-', gen_salt('bf')), 'student', 3),
('Flueraru Alexandru-Achille', 'alexandru-achille.flueraru@s.unibuc.ro', crypt('W@?ZEAnCGjG-@aN9', gen_salt('bf')), 'student', 3),
('Găină David', 'david.gaina@s.unibuc.ro', crypt('*b2P#5xrsemvXJ-G', gen_salt('bf')), 'student', 3),
('Neculae Mara-Daniela', 'mara-daniela.neculae@s.unibuc.ro', crypt('ZYGSyVKsuS@c@jTX', gen_salt('bf')), 'student', 3),
('Negrilă Ștefan', 'stefan.negrila@s.unibuc.ro', crypt('AmC$7aS9W?hu3Hfe', gen_salt('bf')), 'student', 3),
('Pelea Radu-Ștefan', 'radu-stefan.pelea@s.unibuc.ro', crypt('WWn27*H+4VAP4EaS', gen_salt('bf')), 'student', 3),
('Rusănescu Gabriel', 'gabriel.rusanescu@s.unibuc.ro', crypt('Y3bb6-GF-HsZM4N@', gen_salt('bf')), 'student', 3),
('Ruse Alexandru-Cristian', 'alexandru-cristian.ruse@s.unibuc.ro', crypt('+%Y6%4@Tav-vmnm9', gen_salt('bf')), 'student', 3),
('Sarofin Cristian-Constantin', 'cristian-constantin.sarofin@s.unibuc.ro', crypt('eu+HmEKQxqfT$4z2', gen_salt('bf')), 'student', 3),
('Sîrbu Iulia-Georgiana', 'iulia-georgiana.sirbu@s.unibuc.ro', crypt('Vc-zNGFf+DwX9Vws', gen_salt('bf')), 'student', 3),
('Stîngă David-Andrei', 'david-andrei.stinga@s.unibuc.ro', crypt('FXYQ#MXvHvz?Q?eH', gen_salt('bf')), 'student', 3),
('Sturzoiu Maria-Filofteia', 'maria-filofteia.sturzoiu@s.unibuc.ro', crypt('26n5a2zREHAb+eu3', gen_salt('bf')), 'student', 3),
('Suciu Dragos-Emanuel', 'dragos-emanuel.suciu@s.unibuc.ro', crypt('3PN2$%kjVRP*vrBv', gen_salt('bf')), 'student', 3),
('Udroiu Cristian', 'cristian.udroiu@s.unibuc.ro', crypt('cQJF?!BHvNSNEjqb', gen_salt('bf')), 'student', 3),
('Vișănescu Mihai', 'mihai.visanescu@s.unibuc.ro', crypt('ZVNxdg$cqf-Q?rHv', gen_salt('bf')), 'student', 3),
('Bulubașa Alexia-Elena', 'alexia-elena.bulubasa@s.unibuc.ro', crypt('6a43RX&AH+ZwDM+$', gen_salt('bf')), 'student', 3),
('Cîrciumaru Cristian-Radu', 'cristian-radu.circiumaru@s.unibuc.ro', crypt('+-Z-!TC8G6Jq7WeY', gen_salt('bf')), 'student', 3),
('Constantinescu Florian-Robert', 'florian-robert.constantinescu@s.unibuc.ro', crypt('BKkg4DzvNVzfn3Tf', gen_salt('bf')), 'student', 3),
('Dominte Ștefan-Alexandru', 'stefan-alexandru.dominte@s.unibuc.ro', crypt('aw&w9+yhA9!dsg4@', gen_salt('bf')), 'student', 3),
('Floroiu David-Cristian', 'david-cristian.floroiu@s.unibuc.ro', crypt('2hn5u6!zhDsaE+y3', gen_salt('bf')), 'student', 3),
('Gheorghe Alexa-Andreea', 'alexa-andreea.gheorghe@s.unibuc.ro', crypt('XbEg&ZXy65%c!7CS', gen_salt('bf')), 'student', 3),
('Gheorghe Elena-Rebecca', 'elena-rebecca.gheorghe@s.unibuc.ro', crypt('fu%RZ7t*nnXXTaW6', gen_salt('bf')), 'student', 3),
('Gherghe Ana-Alexandra', 'ana-alexandra.gherghe@s.unibuc.ro', crypt('rA#SWxByA5$YR4Wb', gen_salt('bf')), 'student', 3),
('Gîrlă Monica-Ioana', 'monica-ioana.girla@s.unibuc.ro', crypt('ArrvF8Y#6FQZM6Ax', gen_salt('bf')), 'student', 3),
('Ivan Octavian', 'octavian.ivan@s.unibuc.ro', crypt('E%pm3*npvHPw4k$d', gen_salt('bf')), 'student', 3),
('Matei Thea-Sorana', 'thea-sorana.matei@s.unibuc.ro', crypt('Epv3H5KQpFjT%cj#', gen_salt('bf')), 'student', 3),
('Mihai Alessia-Ioana', 'alessia-ioana.mihai@s.unibuc.ro', crypt('naTJYsR@#!@E!M8A', gen_salt('bf')), 'student', 3),
('Moldovan Raluca-Andreea', 'raluca-andreea.moldovan@s.unibuc.ro', crypt('4Ytkm#GuXkM9q*Mk', gen_salt('bf')), 'student', 3),
('Nan Alexandra-Teodora', 'alexandra-teodora.nan@s.unibuc.ro', crypt('C8sEhpJP8mRNjp2C', gen_salt('bf')), 'student', 3),
('Pădeanu Vlad-Florin', 'vlad-florin.padeanu@s.unibuc.ro', crypt('KB$sBEezY?c-AE9Q', gen_salt('bf')), 'student', 3),
('Ristea Octavian-Cristian', 'octavian-cristian.ristea@s.unibuc.ro', crypt('a#E#RRx!+ua#&$?4', gen_salt('bf')), 'student', 3),
('Rolea Robert-Andrei', 'robert-andrei.rolea@s.unibuc.ro', crypt('PhWS5BQ3RcQcwGC?', gen_salt('bf')), 'student', 3),
('Sebacher Maria-Alexandra', 'maria-alexandra.sebacher@s.unibuc.ro', crypt('@Z*X6Ps4mCYwPvS?', gen_salt('bf')), 'student', 3),
('Stănescu Liviu-Cristian', 'liviu-cristian.stanescu@s.unibuc.ro', crypt('gj@GFnh4bGK-5KGJ', gen_salt('bf')), 'student', 3),
('Argherie Andrei-Codrut', 'andrei-codrut.argherie@s.unibuc.ro', crypt('cSyr8YbSqdK-a8!&', gen_salt('bf')), 'student', 3),
('Boboc Bogdan-Costin', 'bogdan-costin.boboc@s.unibuc.ro', crypt('Kv8qY$HY6DMpA#Tp', gen_salt('bf')), 'student', 3),
('Cimpoeșu Rareș-Ștefan', 'rares-stefan.cimpoesu@s.unibuc.ro', crypt('b9eWzgXGchRPw7!#', gen_salt('bf')), 'student', 3),
('Dorobanțu David-Gabriel', 'david-gabriel.dorobantu@s.unibuc.ro', crypt('Qtq6Qds$G9VYYTjH', gen_salt('bf')), 'student', 3),
('Duță Andrei-George', 'andrei-george.duta@s.unibuc.ro', crypt('wcuqpCMFR4rpn99x', gen_salt('bf')), 'student', 3),
('Iancu Mihnea-Matei', 'mihnea-matei.iancu@s.unibuc.ro', crypt('G5ZJ5!R4JG*DQmvx', gen_salt('bf')), 'student', 3),
('Matache David-Mihai', 'david-mihai.matache@s.unibuc.ro', crypt('KHV#J8uF#mSvKQJW', gen_salt('bf')), 'student', 3),
('Merticariu Vlad-Ștefan', 'vlad-stefan.merticariu@s.unibuc.ro', crypt('af57bVT6UByGrP8?', gen_salt('bf')), 'student', 3),
('Miura Kevin-Adrian', 'kevin-adrian.miura@s.unibuc.ro', crypt('aGnrANrXUS&Da&vW', gen_salt('bf')), 'student', 3),
('Nan Bianca-Maria', 'bianca-maria.nan@s.unibuc.ro', crypt('M4nGgR6mxe%DwEP3', gen_salt('bf')), 'student', 3),
('Petrovici Dalia-Teodora', 'dalia-teodora.petrovici@s.unibuc.ro', crypt('m*4?gV#r+!#e9GU4', gen_salt('bf')), 'student', 3),
('Radu Ioana', 'ioana.radu@s.unibuc.ro', crypt('&+sth!nz7aGuM%Xy', gen_salt('bf')), 'student', 3),
('Răpițeanu Carol-David', 'carol-david.rapiteanu@s.unibuc.ro', crypt('CK%QvpMb!bZH*?ff', gen_salt('bf')), 'student', 3),
('Sabo David', 'david.sabo@s.unibuc.ro', crypt('Wd?4QzSY5a+q93+2', gen_salt('bf')), 'student', 3),
('Ștefan George-Alexandru', 'george-alexandru.stefan@s.unibuc.ro', crypt('WS@zB$Q*!#CPc#EC', gen_salt('bf')), 'student', 3),
('Tatomir Darius-Flavius', 'darius-flavius.tatomir@s.unibuc.ro', crypt('P8?8%sybWXkJc?Ju', gen_salt('bf')), 'student', 3),
('Timbuș Maria-Alexandra', 'maria-alexandra.timbus@s.unibuc.ro', crypt('KYy+bxRnVUTsKmDW', gen_salt('bf')), 'student', 3),
('Trandafir Mariana-Florentina', 'mariana-florentina.trandafir@s.unibuc.ro', crypt('Uzzyr3@wPsphA7nn', gen_salt('bf')), 'student', 3),
('Ungureanu David-Emanuel', 'david-emanuel.ungureanu@s.unibuc.ro', crypt('8f9WSygx%6sZbm9T', gen_salt('bf')), 'student', 3),
('Guillermo Alonso', 'alonso.guillermo@s.unibuc.ro', crypt('+t3$K5DC+sCUtU$+', gen_salt('bf')), 'student', 3),
('Baciu Cristian', 'cristian.baciu@s.unibuc.ro', crypt('&y4H7nKFmcVce5Fv', gen_salt('bf')), 'student', 3),
('Bodescu Nicoleta-Cătălina', 'nicoleta-catalina.bodescu@s.unibuc.ro', crypt('#@Z#PBqfrhaFaR3u', gen_salt('bf')), 'student', 3),
('Ciunel Vlad Cristian', 'vlad-cristian.ciunel@s.unibuc.ro', crypt('gUKkuv&kDTv&gY#5', gen_salt('bf')), 'student', 3),
('Ciută Vasile', 'vasile.ciuta@s.unibuc.ro', crypt('J$n#jZz@M73VP@SB', gen_salt('bf')), 'student', 3),
('Crăciun Daniel', 'daniel.craciun@s.unibuc.ro', crypt('r7wg?f#9r*KCPEXD', gen_salt('bf')), 'student', 3),
('Micu Cosmin-Andrei', 'cosmin-andrei.micu@s.unibuc.ro', crypt('h+Mqenyz&z%zXqHP', gen_salt('bf')), 'student', 3),
('Murariu Tudor-Călin', 'tudor-calin.murariu@s.unibuc.ro', crypt('R!2wE&zs!b+w%Ppf', gen_salt('bf')), 'student', 3),
('Neacșu Rareș Andrei', 'rares-andrei.neacsu@s.unibuc.ro', crypt('TRp#AaqsnneNW!6r', gen_salt('bf')), 'student', 3),
('Necula Matei', 'matei.necula@s.unibuc.ro', crypt('rr4%34U2+2QmJqms', gen_salt('bf')), 'student', 3),
('Nedelcu Liviu-Adrian', 'liviu-adrian.nedelcu@s.unibuc.ro', crypt('mwWenn4RPhCZH*4x', gen_salt('bf')), 'student', 3),
('Oroian Andrei-Cristian', 'andrei-cristian.oroian@s.unibuc.ro', crypt('8kG+Yb53QrtA+FQt', gen_salt('bf')), 'student', 3),
('Pluțu Robert-Adrian', 'robert-adrian.plutu@s.unibuc.ro', crypt('%BwMsEr5C$*Wxch@', gen_salt('bf')), 'student', 3),
('Rada Patrick-Andrei', 'patrick-andrei.rada@s.unibuc.ro', crypt('@?hgG58pr*fHA%xw', gen_salt('bf')), 'student', 3),
('Salehi Arian-Andrei', 'arian-andrei.salehi@s.unibuc.ro', crypt('UNm#3TFJ8e*@uf#5', gen_salt('bf')), 'student', 3),
('Sandu-Popa Eduard-Octavian', 'eduard-octavian.sandu-popa@s.unibuc.ro', crypt('U6DjK%6zruZ7anEw', gen_salt('bf')), 'student', 3),
('Stănică Constantin-Dragoș', 'constantin-dragos.stanica@s.unibuc.ro', crypt('+%Y@a+H3&Qdvf*d5', gen_salt('bf')), 'student', 3),
('Stoica Sara', 'sara.stoica@s.unibuc.ro', crypt('cvp-f4wAz5?G36xU', gen_salt('bf')), 'student', 3),
('Tița Teodor', 'teodor.tita@s.unibuc.ro', crypt('zUSPRtg%Zan?N9#S', gen_salt('bf')), 'student', 3),
('Vișan Miruna-Ștefania', 'miruna-stefania.visan@s.unibuc.ro', crypt('zMgC#TjrjxUY@x3g', gen_salt('bf')), 'student', 3),
('Andrei Cristian Birlogeanu', 'andrei-cristian.birlogeanu@s.unibuc.ro', crypt('domnustudentpa55', gen_salt('bf')), 'student', 3)
ON CONFLICT (email) DO UPDATE
SET password_hash = EXCLUDED.password_hash;